// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvwzronkmfbjqcohrsev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2d3pyb25rbWZianFjb2hyc2V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDcwMTQsImV4cCI6MjA3MzA4MzAxNH0.9s31tDSLEfDxwXDOZ19PRfwH7xXSlZw7jG7RZa1LkvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});